site_name: 'Documentation'
repo_name: 'paycoreio/docs'
repo_url: 'https://github.com/paycoreio/docs/'
copyright: '© 2018-2019 PayCore.io. All Rights Reserved.'
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
  var1: 'test123'
google_analytics:
  - 'UA-72023338-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
- Home:
    - Introduction: 'index.md'
    - Release notes: 'release-notes.md'
- Getting started:
    - Overview: 'getting-started/overview.md'

    - Integration:
        - Overview: 'getting-started/integration/index.md'   
    - User Profile: 
        - Overview: 'getting-started/user-profile/index.md'
        - General: 'getting-started/user-profile/general.md'
        - Security: 'getting-started/user-profile/security.md'
    - Organisation:
        - Overview: 'getting-started/organisation/index.md'
        - General: 'getting-started/organisation/general.md'
        - Security: 'getting-started/organisation/security.md'
        - Access Control: 'getting-started/organisation/access.md'

    - Webhooks: 'getting-started/webhooks.md'
    - API: 'getting-started/api.md'
    - Public IPs: 'ips.md'
- Products:
    - Analytics:
        - Overview: 'products/analytics/overview.md'
        - Queries: 'products/analytics/queries.md'
        - Dashboards: 'products/analytics/dashboards.md'
        - Alerts: 'products/analytics/alerts.md'
    - Provider Hub:
        - Overview: 'products/provider-hub/overview.md'
        - Provider Accounts: 'products/provider-hub/provider-accounts.md'
        - Merchant Accounts: 'products/provider-hub/merchant-accounts.md'
        - Deposit Accounts: 'products/provider-hub/deposit-accounts.md'
    - Payment gateway:
        - Overview: 'products/payment-gateway/overview.md'
        - Payments: 'products/payment-gateway/payments.md'
        - Payment Requests: 'products/payment-gateway/payment-requests.md'
    - Payout gateway:
        - Overview: 'products/payout-gateway/overview.md'
        - Payouts: 'products/payout-gateway/payouts.md'
        - Payout Requests: 'products/payout-gateway/payout-requests.md'
    - Currency rates:
        - Overview: 'products/currency-rates/overview.md'
        - Resources: 'products/currency-rates/resources.md'
        - Rate Schemes: 'products/currency-rates/rate-schemes.md'
    - HPP:
        - Overview: 'products/hpp/overview.md'
    - Commerce:
        - Overview: 'products/commerce/overview.md'
- Providers:
        - Overview: 'payment-providers/index.md'
        - AdvCash:
            - Connection manual: 'payment-providers/advcash/connect-manual.md'
        - AnyCash:
            - Connection manual: 'payment-providers/anycash/connect-manual.md'
        - Certus Finance:
            - Connection manual: 'payment-providers/certusfinance/connect-manual.md'
        - CoinGate:
            - Connection manual: 'payment-providers/coingate/connect-manual.md'
        - FlashPay:
            - Connection manual: 'payment-providers/flashpay/connect-manual.md'
        - Fondy:
            - Connection manual: 'payment-providers/fondy/connect-manual.md'
        - GeoPay:
            - Connection manual: 'payment-providers/geopaynet/connect-manual.md'
        - ING Bank Poland:
            - Connection manual: 'payment-providers/ingbankpl/connect-manual.md'
        - Interkassa:
            - Connection manual: 'payment-providers/interkassa/connect-manual.md'
        - LiqPay:
            - Connection manual: 'payment-providers/liqpay/connect-manual.md'
        - PayBox:
            - Connection manual: 'payment-providers/paybox/connect-manual.md'
        - PayMega:
            - Connection manual: 'payment-providers/paymega/connect-manual.md'
        - SatchelPay:
            - Connection manual: 'payment-providers/satchelpay/connect-manual.md'
        - 123x:
            - Connection manual: 'payment-providers/123x/connect-manual.md'
        - 4bill:
            - Connection manual: 'payment-providers/4bill/connect-manual.md'





