site_name: 'Documentation'
repo_name: 'paycoreio/docs'
repo_url: 'https://github.com/paycoreio/docs/'
copyright: '© 2016-2048 PayCore.io<sup>®</sup>. All Rights Reserved.'
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
  var1: 'test123'
google_analytics:
  - 'UA-72023338-4'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - smarty
nav:
- Getting started:
    - Introduction: 'index.md'   
    - Integration:
        - Overview: 'getting-started/integration/index.md'   
    - FAQ: 'getting-started/faq.md'
    - Glossary: 'getting-started/glossary.md'
- Platform:
    - Dashboard: 'platform/dashboard/index.md'
    - User Profile: 
        - Overview: 'platform/user-profile/index.md'
        - General: 'platform/user-profile/general.md'
        - Security: 'platform/user-profile/security.md'
    - Organisation:
        - Overview: 'platform/organisation/index.md'
        - General: 'platform/organisation/general.md'
        - Security: 'platform/organisation/security.md'
        - Access Control: 'platform/organisation/access.md'
- Products:
    - Overview: 'products/index.md'
    - Provider Hub:
        - Overview: 'products/provider-hub/index.md'
        - Provider Accounts: 'products/provider-hub/provider-accounts.md'
        - Merchant Accounts: 'products/provider-hub/merchant-accounts.md'
        - Deposit Accounts: 'products/provider-hub/deposit-accounts.md'
    - Commerce:
        - Overview: 'products/commerce/index.md'
        - Commerce Account:
          - Overview: 'products/commerce/commerce-account/overview.md'
          - Guide: 'products/commerce/commerce-account/guide.md'
        - Contract Scheme:
          - Overview: 'products/commerce/contract-scheme/overview.md'
          #- Guide:
        - Currency Account:
          - Overview: 'products/commerce/currency-account/overview.md'
          #- Guide:
        - Ledger: 'products/commerce/ledger/overview.md'
        - Operations:
          - Overview: 'products/commerce/operations/overview.md'
          - Payment Invoice:
            - Overview: 'products/commerce/operations/payment-invoice/overview.md'
            - Guide: 'products/commerce/operations/payment-invoice/guide.md'
          - Payout Invoice: 
            - Overview: 'products/commerce/operations/payout-invoice/overview.md'
            - Guide: 'products/commerce/operations/payout-invoice/guide.md'
          - Deposit: 'products/commerce/operations/deposit/overview.md'
          - Withdrawal: 'products/commerce/operations/withdrawal/overview.md'
          - Transfer: 'products/commerce/operations/transfer/overview.md'
        - Commerce Webhooks: 'products/commerce/webhooks.md'
        - SDK Widget: 'products/commerce/sdk-widget/overview.md'
    - Payment gateway:
        - Overview: 'products/payment-gateway/index.md'
        - Payments: 'products/payment-gateway/payments.md'
        - Requests: 'products/payment-gateway/payment-requests.md'
        - Pages: 'products/payment-gateway/payment-pages.md'
        - Routes: 'products/payment-gateway/payment-routes.md'
        - Routing Schemes: 'products/payment-gateway/payment-routing-schemes.md'
    - Payout gateway:
        - Overview: 'products/payout-gateway/index.md'
        - Payouts: 'products/payout-gateway/payouts.md'
        - Requests: 'products/payout-gateway/payout-requests.md'
        - Points: 'products/payout-gateway/payout-points.md'
        - Routes: 'products/payout-gateway/payout-routes.md'
        - Routing Schemes: 'products/payout-gateway/payout-routing-schemes.md'
    - FX Rates:
        - Overview: 'products/fx-rates/index.md'
        - Resources: 'products/fx-rates/resources.md'
        - Rate Schemes: 'products/fx-rates/rate-schemes.md'
    - HPP:
        - Overview: 'products/hpp/index.md'
    - Analytics:
        - Overview: 'products/analytics/index.md'
        - Queries: 'products/analytics/queries.md'
        - Dashboards: 'products/analytics/dashboards.md'
        - Alerts: 'products/analytics/alerts.md'
- Integration: 
    - API References: 'integration/index.md'
    - Public IPs: 'integration/ips.md'
    - Callbacks: 'integration/callbacks.md'
- Connectors:
      - Overview: 'connectors/index.md'
      - 123x: 'connectors/123x/index.md'
      - 4bill: 'connectors/4bill/index.md'
      - AdvCash: 'connectors/advcash/index.md'
      - AnyCash: 'connectors/anycash/index.md'
      #- AustralPay: 'connectors/australpay/index.md'
      - CardPay: 'connectors/cardpay/index.md'
      - Certus Finance: 'connectors/certusfinance/index.md'
      - CoinGate: 'connectors/coingate/index.md'
      #- CoinPayments:'connectors/coinpayments/index.md'
      - dLocal: 'connectors/dlocal/index.md'
      - FlashPay: 'connectors/flashpay/index.md'
      - Fondy: 'connectors/fondy/index.md'
      - GeoPay: 'connectors/geopaynet/index.md'
      - ING Bank Poland: 'connectors/ingbankpl/index.md'
      - Interkassa: 'connectors/interkassa/index.md'
      #- Leogaming: 'connectors/leogaming/index.md'
      - LiqPay: 'connectors/liqpay/index.md'
      #- MoneyMovers: 'connectors/moneymovers/index.md'
      - Neteller: 'connectors/neteller/index.md'
      - Parimatch: 'connectors/parimatch/index.md'
      - PayBox: 'connectors/paybox/index.md'
      - Payeer: 'connectors/payeer/index.md'
      - PayMega: 'connectors/paymega/index.md'
      - PayMega.io: 'connectors/paymegaio/index.md'
      - PaymentCenter: 'connectors/paymentcenter/index.md'   
      #- Payoneer: 'connectors/payoneer/index.md'
      - PayPal: 'connectors/paypal/index.md'
      - PaySec: 'connectors/paysec/index.md'
      - PerfectMoney: 'connectors/perfectmoney/index.md'
      - Piastrix: 'connectors/piastrix/index.md'
      - SatchelPay: 'connectors/satchelpay/index.md'
      - Skrill: 'connectors/skrill/index.md'
      - Tranzzo: 'connectors/tranzzo/index.md'
      - Wirecapital: 'connectors/wirecapital/index.md'
      - Xpay: 'connectors/xpayua/index.md'
- Release notes: 
    - Overview: 'release-notes/index.md'
    - v0.58 (23/03/2019): 'release-notes/v0.58.md'
    - v0.57 (11/03/2019): 'release-notes/v0.57.md'
    - v0.56 (05/03/2019): 'release-notes/v0.56.md' 




