name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.9'
      - run: python -m pip install --upgrade pip 
      
      - name: Install theme
        run: |
          pip3 install -r requirements.txt

      - name: Build docs
        run:  |
          git clean -fdx
          mkdocs build -c

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2 
        with: 
          python-version: '3.9'
      - run: python -m pip install --upgrade pip

      - name: Install theme
        run: | 
          pip install -r requirements.txt

      - name: Deploy docs
        run: |
          mkdocs gh-deploy -c --force
          mkdocs --version
